title: Emmanuel Adegbola
description: Data Scientist applying machine learning and statistical modeling to biological processes
url: https://mininuel.github.io

author:
  name: Emmanuel Adegbola

github_username: mininuel
linkedin_username: Emmanuel Oluwafemi Adegbola 
X_handle: @defenceministe

theme: minima
markdown: kramdown

plugins:
  - jekyll-feed
